### ISSUE TITLE
Support scipy >= 1.9

### ISSUE THREAD

**Issue by ErinWeisbart** [cytomining/pycytominer#259]
Pinned scipy to <1.9 in #258 because pycytominer aggregate calls median_absolute_deviation from scipy.stats and median_absolute_deviation was removed from scipy.stats in 1.9.0

Currently if I run `from pycytominer import aggregate` with `scipy == 1.10.0` I get the error `ImportError: cannot import name 'median_absolute_deviation' from 'scipy.stats'`

**Comment by williamdee1** [comment]
Hello, I had the same issue, you can correct it by navigating to your folder where pycytominer is, then in the operations folder there is a file called transform.py. Alter the import in transform.py as follows:

delete --> from scipy.stats import median_absolute_deviation
insert --> from scipy.stats import median_abs_deviation

This works on my current version of scipy (1.10.1).

**Comment by gwaybio** [comment]
Thanks for the note @williamdee1 - also see #258 where @ErinWeisbart solved this in the import.

Do you think it's worth making the change you describe in the source code and then dropping the lower scipy version in the requirements? Erin, what do you think?

**Comment by williamdee1** [comment]
Hi @gwaybio :)

Personally, yes, I would make the change, as I think it's better to require the user to update to the latest version of a dependent package (especially one as big as scipy) than to potentially downgrade.

**Comment by ErinWeisbart** [comment]
Yep! I agree we should support the most current version of scipy. 
`median_abs_deviation` was introduced in 1.5.0 so requirements will need to change to `scipy>=1.5.0`

**Comment by williamdee1** [comment]
If you change the import, then the class RobustMAD within the transform.py file will also have to be altered:

self.mad = pd.Series(
            **median_abs_deviation**(X, nan_policy="omit"), index=self.median.index
        )

**Comment by gwaybio** [comment]
Let's do it! @williamdee1 - would you be able to file a PR?

**Comment by williamdee1** [comment]
Sure thing, will do it tomorrow morning (am on UK time) 👍

**Comment by williamdee1** [comment]
Hi @gwaybio the changes I've suggested above are actually already in the master branch on GitHub, however they are not currently in the latest release (0.2.0) of pycytominer. So I guess those will come through in the next released version...
